version: 2
project_name: netbox-go-discovery

before:
  hooks:
    - go mod download

builds:
  - binary: netbox-go-discovery
    main: ./cmd/netbox-go-discovery/main.go
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: true
    formats: ["tar.gz"]
    files:
      - LICENSE
      - README.md

changelog:
  sort: desc
  filters:
    exclude:
      - "^MERGE"

release:
  github:
    owner: tranceh2
    name: netbox-go-discovery

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
